### Predicting  Youtube Spam or Ham In Python
+ Sklearn
+ Pandas

##### Idea: Converting Words into Vectors to Use as Features to help in classification

In [5]:
# EDA Packages
import pandas as pd
import numpy as np


In [6]:
# ML Packages For Vectorization of Text For Feature Extraction
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [7]:
# Visualization Packages
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
# Dataset from https://archive.ics.uci.edu/ml/datasets/YouTube+Spam+Collection#
df1 = pd.read_csv("Youtube01-Psy.csv")

In [9]:
df1.head()

COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [10]:
# Load all our dataset to merge them
df2 = pd.read_csv("Youtube02-KatyPerry.csv")
df3 = pd.read_csv("Youtube03-LMFAO.csv")
df4 = pd.read_csv("Youtube04-Eminem.csv")
df5 = pd.read_csv("Youtube05-Shakira.csv")

In [11]:
frames = [df1,df2,df3,df4,df5]

In [12]:
# Merging or Concatenating our DF
df_merged = pd.concat(frames)

In [13]:
df_merged

COMMENT_ID                AUTHOR  \
0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU             Julius NM   
1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A           adam riyati   
2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8      Evgeny Murashkin   
3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04       ElNino Melendez   
4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw                GsMega   
..                                           ...                   ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA          Katie Mettam   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI  Sabina Pearson-Smith   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs         jeffrey jules   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0        Aishlin Maciel   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA           Latin Bosch   

                           DATE  \
0           2013-11-07T06:20:48   
1           2013-11-07T12:37:15   
2           2013-11-08T17:34:21   
3           2013-11-09T08:28:43   
4           2013-11-10T16:05:38   
..                          ...   
365  2013-07-13T13:27:39.441000   
366  2013-07-13T13:14:30.021000   
367  2013-07-13T12:09:31.188000   
368  2013-07-13T11:17:52.308000   
369  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0    Huh, anyway check out this you[tube] channel: ...      1  
1    Hey guys check out my new channel and our firs...      1  
2               just for test I have to say murdev.com      1  
3     me shaking my sexy ass on my channel enjoy ^_^       1  
4              watch?v=vtaRGgvGtWQ   Check this out .      1  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [14]:
# Total Size
df_merged.shape

(1956, 5)

In [15]:
# Merging with Keys
keys = ["Psy","KatyPerry","LMFAO","Eminem","Shakira"]

In [16]:
df_with_keys = pd.concat(frames,keys=keys)

In [17]:
df_with_keys

COMMENT_ID  \
Psy     0    LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU   
        1    LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A   
        2    LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8   
        3            z13jhp0bxqncu512g22wvzkasxmvvzjaz04   
        4            z13fwbwp1oujthgqj04chlngpvzmtt3r3dw   
...                                                  ...   
Shakira 365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA   
        366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI   
        367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs   
        368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0   
        369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA   

                           AUTHOR                        DATE  \
Psy     0               Julius NM         2013-11-07T06:20:48   
        1             adam riyati         2013-11-07T12:37:15   
        2        Evgeny Murashkin         2013-11-08T17:34:21   
        3         ElNino Melendez         2013-11-09T08:28:43   
        4                  GsMega         2013-11-10T16:05:38   
...                           ...                         ...   
Shakira 365          Katie Mettam  2013-07-13T13:27:39.441000   
        366  Sabina Pearson-Smith  2013-07-13T13:14:30.021000   
        367         jeffrey jules  2013-07-13T12:09:31.188000   
        368        Aishlin Maciel  2013-07-13T11:17:52.308000   
        369           Latin Bosch  2013-07-12T22:33:27.916000   

                                                       CONTENT  CLASS  
Psy     0    Huh, anyway check out this you[tube] channel: ...      1  
        1    Hey guys check out my new channel and our firs...      1  
        2               just for test I have to say murdev.com      1  
        3     me shaking my sexy ass on my channel enjoy ^_^       1  
        4              watch?v=vtaRGgvGtWQ   Check this out .      1  
...                                                        ...    ...  
Shakira 365  I love this song because we sing it at Camp al...      0  
        366  I love this song for two reasons: 1.it is abou...      0  
        367                                                wow      0  
        368                            Shakira u are so wiredo      0  
        369                         Shakira is the best dancer      0  

[1956 rows x 5 columns]

In [18]:
# Checking for Only Comments on Shakira
df_with_keys.loc['Shakira']

COMMENT_ID  \
0            z13lgffb5w3ddx1ul22qy1wxspy5cpkz504   
1              z123dbgb0mqjfxbtz22ucjc5jvzcv3ykj   
2          z12quxxp2vutflkxv04cihggzt2azl34pms0k   
3              z12icv3ysqvlwth2c23eddlykyqut5z1h   
4              z133stly3kete3tly22petvwdpmghrlli   
..                                           ...   
365  _2viQ_Qnc6-bMSjqyL1NKj57ROicCSJV5SwTrw-RFFA   
366  _2viQ_Qnc6-pY-1yR6K2FhmC5i48-WuNx5CumlHLDAI   
367  _2viQ_Qnc6_k_n_Bse9zVhJP8tJReZpo8uM2uZfnzDs   
368  _2viQ_Qnc6_yBt8UGMWyg3vh0PulTqcqyQtdE7d4Fl0   
369  _2viQ_Qnc685RPw1aSa1tfrIuHXRvAQ2rPT9R06KTqA   

                                 AUTHOR                        DATE  \
0                            dharma pal  2015-05-29T02:30:18.971000   
1                         Tiza Arellano  2015-05-29T00:14:48.748000   
2    Prìñçeśś Âliś Łøvê Dømíñø Mâđiś™   2015-05-28T21:00:08.607000   
3                         Eric Gonzalez  2015-05-28T20:47:12.193000   
4                         Analena López  2015-05-28T17:08:29.827000   
..                                  ...                         ...   
365                        Katie Mettam  2013-07-13T13:27:39.441000   
366                Sabina Pearson-Smith  2013-07-13T13:14:30.021000   
367                       jeffrey jules  2013-07-13T12:09:31.188000   
368                      Aishlin Maciel  2013-07-13T11:17:52.308000   
369                         Latin Bosch  2013-07-12T22:33:27.916000   

                                               CONTENT  CLASS  
0                                           Nice song      0  
1                                        I love song       0  
2                                        I love song       0  
3    860,000,000 lets make it first female to reach...      0  
4                        shakira is best for worldcup      0  
..                                                 ...    ...  
365  I love this song because we sing it at Camp al...      0  
366  I love this song for two reasons: 1.it is abou...      0  
367                                                wow      0  
368                            Shakira u are so wiredo      0  
369                         Shakira is the best dancer      0  

[370 rows x 5 columns]

In [19]:
# Save and Write Merged Data to csv
df_with_keys.to_csv("YoutubeSpamMergeddata.csv")

In [20]:
df = df_with_keys

In [21]:
df.size

9780

#### Data Cleaning

In [22]:
# Checking for Consistent Column Name
df.columns

Index(['COMMENT_ID', 'AUTHOR', 'DATE', 'CONTENT', 'CLASS'], dtype='object')

In [23]:
# Checking for Datatypes
df.dtypes

COMMENT_ID    object
AUTHOR        object
DATE          object
CONTENT       object
CLASS          int64
dtype: object

In [24]:
# Check for missing nan
df.isnull().isnull().sum()

COMMENT_ID    0
AUTHOR        0
DATE          0
CONTENT       0
CLASS         0
dtype: int64

In [25]:
# Checking for Date
df["DATE"]

Psy      0             2013-11-07T06:20:48
         1             2013-11-07T12:37:15
         2             2013-11-08T17:34:21
         3             2013-11-09T08:28:43
         4             2013-11-10T16:05:38
                           ...            
Shakira  365    2013-07-13T13:27:39.441000
         366    2013-07-13T13:14:30.021000
         367    2013-07-13T12:09:31.188000
         368    2013-07-13T11:17:52.308000
         369    2013-07-12T22:33:27.916000
Name: DATE, Length: 1956, dtype: object

In [26]:
df.AUTHOR
# Convert the Author Name to First Name and Last Name
#df[["FIRSTNAME","LASTNAME"]] = df['AUTHOR'].str.split(expand=True)

Psy      0                 Julius NM
         1               adam riyati
         2          Evgeny Murashkin
         3           ElNino Melendez
         4                    GsMega
                        ...         
Shakira  365            Katie Mettam
         366    Sabina Pearson-Smith
         367           jeffrey jules
         368          Aishlin Maciel
         369             Latin Bosch
Name: AUTHOR, Length: 1956, dtype: object

#### Working With Text Content

In [27]:
df_data = df[["CONTENT","CLASS"]]

In [28]:
df_data.columns

Index(['CONTENT', 'CLASS'], dtype='object')

In [29]:
df_x = df_data['CONTENT']
df_y = df_data['CLASS']

#### Feature Extraction From Text
+ CountVectorizer
+ TfidfVectorizer

In [30]:
cv = CountVectorizer()
ex = cv.fit_transform(["Great song but check this out","What is this song?"])

In [31]:
ex.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 1, 1, 1]], dtype=int64)

In [32]:
cv.get_feature_names()

['but', 'check', 'great', 'is', 'out', 'song', 'this', 'what']

In [33]:
# Extract Feature With CountVectorizer
corpus = df_x
cv = CountVectorizer()
X = cv.fit_transform(corpus) # Fit the Data

In [34]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [35]:
# get the feature names
cv.get_feature_names()

['00',
 '000',
 '002',
 '018',
 '02',
 '034',
 '04',
 '047000',
 '05',
 '053012',
 '0687119038',
 '08',
 '09',
 '0cb8qfjaa',
 '0d878a889c',
 '0dbhjzdw0lbsjbi40gxm0d0p5krhv8xinqli53__wqbahs8zx4mjhw5vwrkpxfoeks',
 '0laviqu2b',
 '10',
 '100',
 '1000',
 '10000000',
 '1000000000',
 '100000415527985',
 '100005244783212',
 '100007085325116',
 '10001',
 '100877300245414',
 '101721377578919894134',
 '10200253113705769',
 '1030',
 '104999962146104962510',
 '10626048',
 '10626835',
 '106865403',
 '107297364',
 '1073741825',
 '1073741828',
 '1073741830',
 '1073741943',
 '108k',
 '109',
 '10b35481',
 '11',
 '1111',
 '1111111111111111111',
 '111719098841907',
 '111982027348137311818',
 '112720997191206369631',
 '11cpwb',
 '11th',
 '12',
 '123',
 '124',
 '124923004',
 '126',
 '127',
 '128gb',
 '12year',
 '13',
 '13017194',
 '131275322914',
 '131338190916',
 '1337',
 '1340488',
 '1340489',
 '1340490',
 '1340491',
 '1340492',
 '1340493',
 '1340494',
 '1340499',
 '1340500',
 '1340502',
 '1340503',
 '134

### Model Building

In [36]:

from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(X, df_y, test_size=0.33, random_state=42)

In [38]:
X_train

<1310x4454 sparse matrix of type '<class 'numpy.longlong'>'
	with 17525 stored elements in Compressed Sparse Row format>

In [39]:
# Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9195046439628483

In [40]:
# Accuracy of our Model
print("Accuracy of Model",clf.score(X_test,y_test)*100,"%")

Accuracy of Model 91.95046439628483 %


In [41]:
## Predicting with our model
clf.predict(X_test)

array([0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,

In [42]:
# Sample Prediciton
comment = ["Check this out"]
vect = cv.transform(comment).toarray()

In [43]:
clf.predict(vect)

array([1])

In [44]:
class_dict = {'ham':0,'spam':1}

In [45]:
class_dict.values()

dict_values([0, 1])

In [46]:
if clf.predict(vect) == 1:
    print("Spam")
else:
    print("Ham")

Spam


In [47]:
# Sample Prediciton 2
comment1 = ["Great song Friend"]
vect = cv.transform(comment1).toarray()
clf.predict(vect)


array([0])

### Save the Model 

In [48]:
import pickle

In [49]:
naivebayesML = open("YtbSpam_model.pkl","wb")

In [50]:
pickle.dump(clf,naivebayesML)

In [51]:
naivebayesML.close()

In [52]:
# Load the model

In [53]:
ytb_model = open("YtbSpam_model.pkl","rb")

In [54]:
new_model = pickle.load(ytb_model)

In [55]:
new_model

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [56]:
# Sample Prediciton 3
comment2 = ["Hey Music Fans I really appreciate all of you,but see this song too"]
vect = cv.transform(comment2).toarray()
new_model.predict(vect)

array([1])

In [57]:
if new_model.predict(vect) == 1:
    print("Spam")
else:
    print("Ham")

Spam


In [ ]:
## Thanks
# Jesus Saves @ JCharisTech
# By Jesse JCharis
# J-Secur1ty