### import lib

#### zxcvbn

In [1]:
from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import Normalizer, StandardScaler, PolynomialFeatures

from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error, mean_squared_log_error

import pandas as pd

import numpy as np 

from matplotlib import pyplot as plt

import seaborn as sb

from sklearn.datasets import load_boston

import pprint as p

from math import sqrt

In [12]:
boston_dataset = load_boston()
boston_dataset1 = load_boston

In [13]:
# print(boston_dataset)
# print(boston_dataset1)

### dtchj

In [16]:
print(boston_dataset.keys())

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])


In [19]:
print(boston_dataset.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [20]:
boston_dataset.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [21]:
boston_dataset.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [25]:
 boston_dataset.target

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [68]:
X = pd.DataFrame(boston_dataset.data , columns = boston_dataset.feature_names )

Y = pd.DataFrame(boston_dataset.target, columns=["Output"])

#or 

X1, Y1 = load_boston(return_X_y=True)


In [46]:
X.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD        float64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
dtype: object

In [47]:
Y.dtypes

Output    float64
dtype: object

In [70]:
print(type(X))
print(type(Y))

print(X.shape)
print(Y.shape)

print("*"*80)

print(type(X1))
print(type(Y1))

print(X1.shape)
print(Y1.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(506, 13)
(506, 1)
********************************************************************************
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(506, 13)
(506,)


In [49]:
X.head(1)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  
0  396.9   4.98

In [50]:
Y.head(1)

Output
0    24.0

In [64]:
# df = pd.merge([X, Y], left_index= True)

# df = X.merge(Y, on== "left") 

#Check merge is not working (why error)


In [56]:
df1 = pd.concat([X, Y], axis=1)
df1.head(1)

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  Output  
0  396.9   4.98    24.0

In [94]:
x_train, x_test, y_train, y_test = train_test_split(X, Y , test_size = 0.2, random_state = 4)

In [74]:
model = LinearRegression()

model

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [77]:
m= model.fit(x_train, y_train)
m

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [91]:
predict_x = model.predict(x_test)
print(predict_x.shape)
print(predict_x.dtype)
print(type(predict_x))
print(type(predict_x.shape))

print("*"*80)

print(type(x_test))
print(type(x_test.shape))
print(x_train.shape)
#print(type(x_test[0])) # error

(102, 1)
float64
<class 'numpy.ndarray'>
<class 'tuple'>
********************************************************************************
<class 'pandas.core.frame.DataFrame'>
<class 'tuple'>
(404, 13)


In [92]:
print(predict_x)

[[12.07495986]
 [26.9894969 ]
 [17.58803353]
 [18.15584511]
 [36.92091659]
 [25.43267386]
 [31.09256932]
 [19.72549907]
 [19.66103377]
 [22.96358632]
 [28.38841214]
 [28.48925986]
 [18.99690357]
 [32.41097504]
 [21.52350275]
 [15.25945122]
 [21.23364112]
 [11.6220597 ]
 [11.37109662]
 [13.63515584]
 [ 5.62431971]
 [17.35323315]
 [20.80951594]
 [22.51311312]
 [16.39055556]
 [20.32352451]
 [17.88994185]
 [14.23445109]
 [21.1187098 ]
 [17.50765806]
 [14.54295525]
 [23.63289896]
 [34.32419647]
 [22.23027161]
 [16.82396516]
 [20.16274383]
 [30.67665825]
 [35.61882904]
 [23.50372003]
 [24.66451121]
 [36.91269871]
 [32.33290254]
 [19.11785719]
 [32.19546605]
 [33.42795148]
 [25.52705821]
 [40.63477427]
 [18.21762788]
 [19.34587461]
 [23.80167377]
 [33.42122982]
 [26.1451108 ]
 [18.10363121]
 [28.19906437]
 [13.37486655]
 [23.34019279]
 [24.44952678]
 [33.54973856]
 [16.71263275]
 [36.56402224]
 [15.69684554]
 [18.55447039]
 [32.14543203]
 [15.49568061]
 [39.02363234]
 [27.38174402]
 [31.96333

In [96]:
accuracy = r2_score(y_test , predict_x)
print(accuracy)

0.7263451459702503


In [104]:
MAE = mean_absolute_error(y_test , predict_x)
MSE = mean_squared_error(y_test , predict_x)
MSLE = mean_squared_log_error(y_test , predict_x) # mean sequare log error

RMSE = np.sqrt(MSE) # or RMSE = sqrt(MSE)
 

In [110]:
print("MAE  : ", MAE)
print("MSE  : ", MSE)
print("MSLE : ", MSLE)

print("RMSE : ", RMSE)


MAE  :  3.3677909837965796
MSE  :  25.41958712682191
MSLE :  0.03768869076769671
RMSE :  5.041784121402057


In [124]:
print("MAE  : %f\nMSE  : %f\nMSLE : %f\nRMSE : %F"%(MAE, MSE, MSLE, RMSE)) # %f or %F

MAE  : 3.367791
MSE  : 25.419587
MSLE : 0.037689
RMSE : 5.041784


In [125]:
print("{MAE  : }, {MSE  : }".format(MAE, MSE))

KeyError: 'MAE  '

# Polynomial Feature

In [115]:
poly_deg_2 = PolynomialFeatures(degree=2)
poly_x_train = poly_deg_2.fit_transform(x_train)
poly_x_test = poly_deg_2.transform(x_test)

In [119]:
model_linear_poly= LinearRegression()
model_linear_poly.fit(poly_x_train, y_train)
model_linear_poly

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [120]:
predict_x_poly = model_linear_poly.predict(poly_x_test)
predict_x_poly

array([[14.13836098],
       [20.96857595],
       [16.00383425],
       [27.90458345],
       [42.45912504],
       [29.6331358 ],
       [32.31564999],
       [17.4035244 ],
       [13.77465582],
       [ 7.47317171],
       [26.71329069],
       [30.28001451],
       [ 5.84319544],
       [35.50941849],
       [21.71866655],
       [10.18497896],
       [20.62191057],
       [11.73146057],
       [15.02927399],
       [ 9.84592295],
       [-5.74184942],
       [19.18593407],
       [18.42313862],
       [20.29263353],
       [16.83149004],
       [19.40340614],
       [26.26445103],
       [17.43382025],
       [18.77905893],
       [21.44256115],
       [15.00426626],
       [21.7625165 ],
       [33.7900362 ],
       [22.17863989],
       [17.39248514],
       [13.72604275],
       [31.7878499 ],
       [40.52387285],
       [24.24325848],
       [25.42288399],
       [44.8551321 ],
       [35.52146149],
       [17.667377  ],
       [31.34153795],
       [27.60453176],
       [18

In [130]:
MAE_Poly = mean_absolute_error(y_test , predict_x_poly)
MSE_Poly = mean_squared_error(y_test , predict_x_poly)
# MSLE_Poly = mean_squared_log_error(y_test , predict_x_poly) # MSLE can not be used when targets contains -ve values. 

RMSE_Poly = np.sqrt(MSE_Poly) # or RMSE = sqrt(MSE)

In [139]:
print("MAE_Poly  : %f\nMSE_Poly  : %f\nRMSE_Poly : %F"%(MAE_Poly, MSE_Poly, RMSE_Poly))
print("MAE  : %f\nMSE  : %f\nMSLE : %f\nRMSE : %F"%(MAE, MSE, MSLE, RMSE)) # %f or %F

MAE_Poly  : 3.563761
MSE_Poly  : 25.369577
RMSE_Poly : 5.036822
MAE  : 3.367791
MSE  : 25.419587
MSLE : 0.037689
RMSE : 5.041784


In [142]:
accuracy = r2_score(y_test , predict_x)
print(accuracy * 100)


Accuracy_Poly = r2_score(y_test , predict_x_poly)
print(Accuracy_Poly * 100)

72.63451459702503
72.68835299738494
